const menuList = [
  {
    id: 1,
    menu: 'BlackForest',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/BlackForedt.jpg',
    price: '75Birr',
    type: 'Cakes',
  },
  {
    id: 2,
    menu: 'corassent',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/corassent.jpg',
    price: '50Birr',
    type: 'Cakes',
  },
  {
    id: 3,
    menu: 'Orange',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Orange.jpg',
    price: '50Birr',
    type: 'Cakes',
  },
  {
    id: 4,
    menu: 'WhiteTorta',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/WhiteTorta.jpg',
    price: '75Birr',
    type: 'Torta',
  },
  {
    id: 5,
    menu: 'Macchiato',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Macchiato.jpg',
    price: '75Birr',
    type: 'Hot Drinks',
  },
  {
    id: 6,
    menu: 'SpecialTea',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/SpecialTea.jpg',
    price: '50Birr',
    type: 'Hot Drinks',
  },
  {
    id: 7,
    menu: 'Milk',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/milk.jpg',
    price: '40Birr',
    type: 'Hot Drinks',
  },
  {
    id: 8,
    menu: 'Spreeze',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Spreeze.jpg',
    price: '75Birr',
    type: 'Hot Drinks',
  },
  {
    id: 9,
    menu: 'Tea',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Tea.jpg',
    price: '75Birr',
    type: 'Hot Drinks',
  },
  {
    id: 10,
    menu: 'Millefoglie',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/SpecialTea.jpg',
    price: '50Birr',
    type: 'Cakes',
  },
  {
    id: 11,
    menu: 'Milkcoffee',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/milk.jpg',
    price: '40Birr',
    type: 'Torta',
  },
  {
    id: 12,
    menu: 'VanillaTorta',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Spreeze.jpg',
    price: '75Birr',
    type: 'Torta',
  },
  {
    id: 13,
    menu: 'BilosSpecial',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/BilosSpecial.jpg',
    price: '75Birr',
    type: 'Torta',
  },
  {
    id: 14,
    menu: 'BoxegnaPuff',
    description: 'coloring tekorach,creams yougert',
    img: '/MenuImages/Boxegnapuff.jpg',
    price: '75Birr',
    type: 'Cakes',
  },
];
export default menuList;
